#ifndef DAC_WAVEFORM_H
#define DAC_WAVEFORM_H

#include <stdbool.h>
#include <stdint.h>

#define DAC_WAVEFORM_FREQUENCY_HZ (50000U)
#define DAC_WAVEFORM_SAMPLE_RATE_HZ (1000000U)
#define DAC_WAVEFORM_DUTY_PERMILLE (350U)
#define DAC_WAVEFORM_RLC_BANDPASS_CENTER_HZ (159155U)
#define DAC_WAVEFORM_RLC_BANDPASS_R_OHM (1000U)
#define DAC_WAVEFORM_RLC_BANDPASS_C_PF (1000U)
#define DAC_WAVEFORM_RLC_BANDPASS_L_UH (1000U)
#define DAC_WAVEFORM_DAC_MID_CODE (2048U)
#define DAC_WAVEFORM_DAC_AMPLITUDE_CODE (1800U)
#define DAC_WAVEFORM_SAMPLE_COUNT \
    (DAC_WAVEFORM_SAMPLE_RATE_HZ / DAC_WAVEFORM_FREQUENCY_HZ)
#define DAC_WAVEFORM_HIGH_SAMPLES \
    ((DAC_WAVEFORM_SAMPLE_COUNT * DAC_WAVEFORM_DUTY_PERMILLE + 500U) / 1000U)

void DacWaveform_Init(void);
void DacWaveform_SetEnabled(bool enabled);
bool DacWaveform_IsEnabled(void);

#endif
